name: Common NodeJS CI Workflow

on:
  workflow_call:
    inputs:
      node-version:
        description: "Node version to use, default to LTS Fermium (14.x)"
        required: true
        type: string

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: appsby8/common-workflows/setup-node@main
        with:
          node-version: ${{ inputs.node-version }}

  lint:
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: appsby8/common-workflows/setup-node@main
        with:
          node-version: ${{ inputs.node-version }}

      - run: npm run lint

  build:
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: appsby8/common-workflows/setup-node@main
        with:
          node-version: ${{ inputs.node-version }}

      - run: npm run build --if-present

  test:
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: appsby8/common-workflows/setup-node@main
        with:
          node-version: ${{ inputs.node-version }}

      - run: npm run test
