name: Release NodeJS Library

on:
  workflow_dispatch:
    inputs:
      node-version:
        description: "Node version to use, default to LTS Fermium (14.x)"
        required: true
        type: string

jobs:

  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: appsby8/common-workflows/setup-node@main
        with:
          node-version: ${{ inputs.node-version }}

      - name: "Automated Version Bump"
        id: version-bump
        uses: "phips28/gh-action-bump-version@master"
        with:
          tag-prefix: 'v'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: 'Output Step'
        env:
          NEW_TAG: ${{ steps.version-bump.outputs.newTag }}
        run: echo "new tag $NEW_TAG"

#  package:
#    runs-on: ubuntu-latest
#    needs: [ release ]
#
#    steps:
#      - uses: actions/checkout@v2
#
#      - uses: appsby8/common-workflows/setup-node@main
#        with:
#          node-version: ${{ inputs.node-version }}
#
#      - run: npm ci
#      - run: npm pack
#      - name: Upload
#        uses: actions/upload-artifact@v2
#        with:
#          name: package
#          path: "*.tgz"
#


        #   package:
#     runs-on: ubuntu-latest
#     needs: [ release ]
#     steps:
#       - uses: actions/checkout@v2
#       - name: Use Node.js 14.x
#         uses: actions/setup-node@v2
#         with:
#           node-version: 14.x
#       - run: npm ci
#       - run: npm pack
#       - name: Upload
#         uses: actions/upload-artifact@v2
#         with:
#           name: package
#           path: "*.tgz"
#
