name: Release NodeJS Library

on:
  workflow_call:
    inputs:
      node-version:
        description: "Node version to use, default to LTS Fermium (14.x)"
        required: true
        type: string
    secrets:
      gh_auth_token:
        description: "Github Auth Token"
        required: true
jobs:

  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: appsby8/common-workflows/setup-node@main
        with:
          node-version: ${{ inputs.node-version }}

      - uses: appsby8/common-workflows/release-nodejs-library@main
        id: release-library
        with:
          node-version: ${{ inputs.node-version }}
          gh-token: ${{ secrets.gh_auth_token }}

      - run: echo ${{ steps.release-library.outputs.release-tag }}
      - run: npm ci
      - run: npm pack
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: ${{github.sha}}
          path: "*.tgz"

  publish:
    name: "Publish to GitHub Packages"
    needs: [ release ]
    runs-on: ubuntu-latest
    steps:
      - name: Download package
        uses: actions/download-artifact@v2
        with:
          name: ${{github.sha}}
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
          registry-url: https://npm.pkg.github.com/
          scope: "@appsby8"
      - run: echo "registry=https://npm.pkg.github.com/@appsby8" >> .npmrc
      - run: npm publish $(ls *.tgz)
        env:
          NODE_AUTH_TOKEN: ${{ secrets.gh_auth_token }}