name: Release NodeJS Library

on:
  workflow_call:
    inputs:
      node-version:
        description: "Node version to use, default to LTS Fermium (14.x)"
        required: true
        type: string

jobs:

  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: appsby8/common-workflows/setup-node@main
        with:
          node-version: ${{ inputs.node-version }}

      - uses: appsby8/common-workflows/release-nodejs-library@main
        with:
          node-version: ${{ inputs.node-version }}
          gh-token: ${{ secrets.GITHUB_TOKEN }}

      - run: "echo ${{ steps.release-nodejs.outputs.release-tag }}"

  # package:


  # publish:


#  package:
#    runs-on: ubuntu-latest
#    needs: [ release ]
#
#    steps:
#      - uses: actions/checkout@v2
#
#      - uses: appsby8/common-workflows/setup-node@main
#        with:
#          node-version: ${{ inputs.node-version }}
#
#      - run: npm ci
#      - run: npm pack
#      - name: Upload
#        uses: actions/upload-artifact@v2
#        with:
#          name: package
#          path: "*.tgz"
#


        #   package:
#     runs-on: ubuntu-latest
#     needs: [ release ]
#     steps:
#       - uses: actions/checkout@v2
#       - name: Use Node.js 14.x
#         uses: actions/setup-node@v2
#         with:
#           node-version: 14.x
#       - run: npm ci
#       - run: npm pack
#       - name: Upload
#         uses: actions/upload-artifact@v2
#         with:
#           name: package
#           path: "*.tgz"
#
